### ISSUE TITLE
[error] 

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/nomad-spark#3]
When i try to use the `hashicorp/spark-nomad` docker image (i.e. when i use cluster mode), i'm getting the following error 
```
Exception in thread "dispatcher-event-loop-0" java.lang.NoSuchFieldError: UPPER_CAMEL_CASE
	at com.hashicorp.nomad.javasdk.NomadJson.<clinit>(NomadJson.java:26)
...
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.hashicorp.nomad.javasdk.NomadJson
	at com.hashicorp.nomad.javasdk.AllocationsApi.info(AllocationsApi.java:46)
```
These errors don't appear when I run directly on my spark distro (non-cluster mode). Could this be caused by a version mismatch?

full stack trace - https://pastebin.com/eDPxqNtc

**Comment by ryanmickler** [comment]
So i discovered that this was due to not having the   `com.fasterxml.jackson.core - jackson-databind` library installed on the container. If i include this in with my deployed app then it works. Perhaps we should include this by default?
